version: '3.8'

services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
      - rabbitmq

    environment:
      - MONGO_URL=mongodb://mongo_db:27017
      - RABBITMQ_URL=rabbitmq
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rabbitmqcon:
    build: ./consumer
    depends_on:
      - rabbitmq
    environment:
    - MONGO_URL=mongo_db
    - RABBITMQ_URL=rabbitmq
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
volumes:
  mongo-data:
  rabbitmq_data: